# docker-compose.yml
version: '3.8'

services:
  frontend:
    build:
      context: ../  # Set the context to the parent directory of .docker, frontend, common, etc.
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  backend:
    build:
      context: ../  # Set the context to the parent directory of .docker, backend, common, etc.
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network



networks:
  app-network:
    driver: bridge
